import = []

working_directory = "None"

live_config_reload = true

ipc_socket = true

[env]
# Environment variables

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Full"
opacity = 0.8
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 16
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
foreground = "#ffffff"
background = "#161616"

[colors.normal]
black   = "#222222"
red     = "#e84f4f"
green   = "#b7ce42"
yellow  = "#fea63c"
blue    = "#66aabb"
magenta = "#b7416e"
cyan    = "#6d878d"
white   = "#dddddd"

[colors.bright]
black   = "#666666"
red     = "#d23d3d"
green   = "#bde077"
yellow  = "#ffe863"
blue    = "#aaccbb"
magenta = "#e16a98"
cyan    = "#42717b"
white   = "#cccccc"

[bell]
animation = "Linear"
duration = 0
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

# Enable specific hints
#[[hints.enabled]]
# Example configuration (actual settings to be defined based on user preference)
# regex = "..."
# hyperlinks = true
# post_processing = true
# persist = false
# action = "..."
# command = "..."
# binding = { key = "...", mods = "...", mode = "..." }
# mouse = { mods = "...", enabled = true }

[keyboard]
bindings = [
    # { key = "Key", mods = "Modifiers", action = "Action" },
    # { key = "Key", mods = "Modifiers", chars = "Characters to send" },
    # ...
]
